version: 0.0
os: linux
files:
  - source: /
    destination: /opt/loginapp
permissions:
  - object: /opt/loginapp/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
