# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        mysql version: '5.7'
        mysql database: 'login'
        mysql user: 'root'
        mysql password: ${{ secrets.MYSQL_DATABASE_PASSWORD }}
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean build
      
    - name: Make Directory for deliver
      run: mkdir deploy
      
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy/
    
    - name: Copy appspec
      run: cp appspec.yml ./deploy/
      
      
    - name: Make zip file
      run: zip -r -qq -j ./springboot-build.zip ./deploy
      
    - name: Deliver to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        ./springboot-build.zip s3://0woodev-springboot-bucket/springboot-build.zip
        
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name login \
        --deployment-group-name springboot-deploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=0woodev-springboot-bucket,bundleType=zip,key=springboot-build.zip \
        --region ap-northeast-2
